apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solar-prod

resources:
  - prometheus/
  - grafana/
  - alertmanager/

labels:
  - pairs:
      app.kubernetes.io/part-of: solar-monitoring
