apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solar-prod

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - rules.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: solar-monitoring
      app.kubernetes.io/component: monitoring
