apiVersion: v1
kind: Service
metadata:
  name: solar-simulator
  labels:
    app: solar-simulator
    app.kubernetes.io/name: solar-simulator
    app.kubernetes.io/component: simulator
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app: solar-simulator
