apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greenwatt.fullname" . }}-config
  namespace: {{ include "greenwatt.namespace" . }}
  labels:
    {{- include "greenwatt.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  PORT: {{ .Values.backend.env.PORT | quote }}
