{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "greenwatt.namespace" . }}
  labels:
    {{- include "greenwatt.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    {{- include "greenwatt.redis.selectorLabels" . | nindent 4 }}
  ports:
  - name: redis
    protocol: TCP
    port: {{ .Values.redis.service.port }}
    targetPort: 6379
{{- end }}
