apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greenwatt.fullname" . }}-secrets
  namespace: {{ include "greenwatt.namespace" . }}
  labels:
    {{- include "greenwatt.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.secrets.DATABASE_URL | quote }}
  REDIS_URL: {{ .Values.backend.secrets.REDIS_URL | quote }}
  POSTGRES_DB: {{ .Values.postgres.env.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.postgres.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.env.POSTGRES_PASSWORD | quote }}
